### ISSUE TITLE
(minor) make link text black (not blue)

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#11]
This may happen in other places too, but on the last page, the link to, say, "Franklin Delano..." shows up blue. Can we make it black? (And as we add other links we'd like them to be black also)

**Comment by smrose** [comment]
There are several types of links, the most important of which are unvisited and visited. Default has long been for unvisited to be blue and visited to be purple. This issue is therefore underspecified. My fix was to make both visited and unvisited black, but if that's not what you want, reopen.
