### ISSUE TITLE
Final page tailored text changes needed — 

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#15]
I'm now realizing that the tailored role / pattern text needs to actually include the pattern name as well as the suggestions. It's there in almost all cases but needs to be changed in a few. I have the changed language but there are two ways to go: (1) I send it you or include it here; or (2) I make the change directly to the database.   I'm assuming that 1b is the preferred route.

**Comment by publicsphere** [comment]
or should I use the translation tool?  I'll be basically out of reach (on Orcas) until late Thursday afternoon. Thanks!

**Comment by smrose** [comment]
I think this is fixed. Some text was misplaced, and the displayed patterns weren't always correct.

To facilitate debugging this, I've introduced a form on the final page that allows a developer to choose which role and four patterns are displayed - independent of the user input. Only those with a developer cookie will see that form.
