### ISSUE TITLE
Saving comments doesn't

### ISSUE THREAD

**Issue by smrose** [smrose/ActivistMirror#16]
A facility is still needed to save the comments that are solicited on the result page.

**Comment by smrose** [comment]
The facility to save comments from the result page is now working. Sadly, it doesn't provide any feedback to the user, so I'll leave this ticket open until I've added that.

**Comment by publicsphere** [comment]
The prompts, etc. from the first page are stored, correct?

**Comment by smrose** [comment]
Yes, they are carried forward through all the question pages, then stored in the 'sessions' record. Of course, we don't have any way to view them. Presume we need a distinct application, akin to the Translate tool, that allows browsing sessions. We've never had that, but now there is more need for it as there is much more data stored in the sessions. In particular, the suggestions could be interesting.

**Comment by smrose** [comment]
Now, I display a sort of poup dialog when suggestions are submitted.
