### ISSUE TITLE
save no match situations so Doug can write new

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#23]
To help me add new role-pattern strings judiciously it would be a nice feature if whenever it was the case that none of the available texts matched the patterns proposed, the session number (or equivalent) was stored in a no-linkage table (and the role supplied the pattern names too). (Or maybe the info could be mailed to me??)

**Comment by smrose** [comment]
I'm thinking that there isn't really any need to store that information separately, as it can be extracted from existing data. What is needed is some sort of interface to browse submissions for this and other purposes. We need a design for that tool.

**Comment by publicsphere** [comment]
Good idea!!  One big table with all the values in it would be great. Ideally we'd be able to hide some fields, sort by some fields, specify date range, etc. — but that could wait. A delete checkbox would be very useful. Ultimately an export option?
