### ISSUE TITLE
the first page is funky... https://analydia.net/publicsphereproject/ActivistMirror/

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#25]
You probably noticed... 
<img width="932" alt="Screenshot 2024-11-10 at 4 26 45 PM" src="https://github.com/user-attachments/assets/9aef920e-30cc-41d7-8e10-4eb1b185e6b5">

**Comment by smrose** [comment]
I hadn't noticed, as I do my testing on a different machine, but I knew what was wrong as soon as I saw that - the CSS file for that first page wasn't in github - and fixed it just now.
