### ISSUE TITLE
add parameters to link!

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#26]
Sorry for late request! But, I think you'd agree that this would be super useful.

https://analydia.net/publicsphereproject/ActivistMirror/?group=gname&project=pname&prompt=prompt

**Comment by smrose** [comment]
I don't know what you are asking for here. I can see that you have added query parameters to the URL of the first page of the application, and that the names of the variables correspond to fields used by the form on pagetwo.php. Why is mysterious.

**Comment by publicsphere** [comment]
Sorry !   I forgot to say that these would be inserted into the fields on page2 as defaults. The user could change them if they wanted but this way we could send a note to people with a certain project and/or group embedded in the url which could help with collaboration and our analysis.

**Comment by smrose** [comment]
I see. That wouldn't be hard to implement. After I finish some work on the language selecting, I'll work on it.

**Comment by smrose** [comment]
Did this.

**Comment by publicsphere** [comment]
Looks good — only one small thing... It might not be a problem because the workaround is simple, but I first tried to add a string that was quoted, e.g. group="the cool group"    But it seems to make the whole thing freeze up (Safari)    So we can remember not to quote things and to backslash special characters, e.g. prompt=what the hell\?
