### ISSUE TITLE
trying to use translate tool  on  ambeta fails

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#27]
https://labs.publicsphereproject.org/am/translate.php => works, but is old version, pre-verbiage table

I went to https://labs.publicsphereproject.org/ambeta/translate.php with safari and firefox. The login box came up and I tried to log in, but failed (I tried multiple times, dumped the cache, and reloaded but never got the login box again.) 

resulting in ....

**Internal Server Error**

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@labs.publicsphereproject.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by smrose** [comment]
The password file was in the wrong place. I moved it and tested that the translate application works and, after fixing another bug, it does.
