### ISSUE TITLE
Presumably you'll move the new strings... 

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#28]
When I get to the translate tool, I'll make changes to the ambeta tables. Then, presumably, you'll move the data to am tables.

This may be obvious but I thought I'd ask.

**Comment by smrose** [comment]
We have two versions of the application - the older "am" version, which uses the "amirror" database, and the in-development "ambeta" version, which uses the "ambeta" database. Each application has its own schema and set of strings. So moving the strings from "ambeta" to "amirror" isn't something that can be done. You should explain what you are hoping to achieve so I can understand why you propose that step and can formulate a plan to achieve the goal via a set of steps that would do it.

**Comment by publicsphere** [comment]
We are now testing on the ambeta version. So, if I make changes to strings via translate.php, won't the changes be made to the ambeta database?  And, if that's the case, won't I have to go in and make all of same changes to the am database?  (I.e. I certainly would need to keep track of them)
