### ISSUE TITLE
sequence of testing... 

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#29]
I believe it will go down like this: (1) I test first (and whatever changes are needed are made) and then (2) we ask our volunteers and other friendlies... [and we'll send them links with parameters... ]   And (3) you'll make the am live and then we can announce it.  Thanks!!!

**Comment by smrose** [comment]
Yes. Step (3) will consist of moving the new application to the former URL (assuming we still like that one) and moving the older version to some other URL so we have it as a reference for a little while. Eventually, we'll sunset the old version just to preserve resources. I'm not clear what limits DreamHost imposes or if we risk approaching them, but presumably there are such limits.

Before we go much further, we should design some means of looking at the submissions. We might learn something from that that informs changes to the design of the application.
