### ISSUE TITLE
The long text fields (such as "prompt" and "suggestion" should be limited in width

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#39]
The long text fields (such as "prompt" and "suggestion" should be limited in width and the person could use the extend box approach like the bottom right of a description field in github.

**Comment by smrose** [comment]
What I'm doing for now is shorting those two strings when > 40 char to 37 char and adding '...' to show that there is more context, and adding a title attribute to the DIV containing the string so that mousing over the DIV displays the full context.
