### ISSUE TITLE
export session data

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#42]
for now it would be great if hard carriage returns were in the export sessions.

In the near future, maybe there should be a column of boxes to click to select records for export. 

ultimately maybe there would be a new page that allowed various filters for exports.

// I can make these three issues

**Comment by smrose** [comment]
Yes, these seem like three distinct issues.

1. I made a submission and for the prompt, I entered a multi-line string. Then I downloaded it, and observed that wherever I had started a new line, a "\r\n" sequence was in the download. Is that what you mean by "hard carriage returns"? If so, why did you think it wasn't happening. If not, what do you mean by "hard carriage returns."

2. My thinking was that you would apply filters to what's displayed in the summary screen and then export that, which is, of course, what we have now. That, I think, obviates the need for a distinct filter page for exports. The only difference between the two pages would be whether you stop at the summary page before exporting.

3. Adding a column of checkboxes to limit which of the summarized are exported is doable, but is it really useful? You can delete rows from whatever tool you import the data into.

**Comment by smrose** [comment]
I'm going to make the assumption that all three issues are resolved by my comments and close this issue, which hasn't seen activity for two weeks.
