### ISSUE TITLE
 In dev role, when patterns bar is used on the AM last page the sessions entry is wrong

### ISSUE THREAD

**Issue by publicsphere** [smrose/ActivistMirror#45]
I used the dev bar with citizen and four patterns that hadn't been displayed and the sessions entry didn't write the role used or the patterns that were revealed. (It listed the first four patterns, "Activist Road Trip,Back to the Roots,Big Tent for Social Change,Citizen Science")  This seems to verify that this is the culprit for all or most of the blank role entries.

**Comment by smrose** [comment]
It's important to understand the purpose and limits are of what I call the "developer toolbar" and you call the "patterns bar."

There are three tables implicated in storing the compound object we think of as a "session": sessions, match_roles, and match_patterns. Users give replies to questions, and from that user input a record in the sessions table is created as a handle and the roles and patterns are ranked and those ranks stored in match_roles and match_patterns. There is nowhere that we directly store the top role and top four patterns - we store the scores (for all four roles and 22 patterns), from which we can always determine what the top role and patterns were that were displayed.

What the developer toolbar does is set the top role and four top patterns (in order) for display to the user - without doing anything to the values stored  in match_patterns or match_roles - which have already been stored before we examine the values in the toolbar. And it also uses those toolbar values to determine which verbiage to display.

So - it's not a "store a session with this role and these patterns" operation - it's a "display this role and these patterns and verbiage to the user" operation. It's done after the session record and all the match_roles and match_patterns values are stored.

The whole, complete, and entire reason I created the toolbar was so you could see what verbiage values would be displayed for your choice of top role and top four patterns. 

Now, as we've seen, there are instances of a session record being created without corresponding match_roles and/or match_patterns records. The sequence of operations in result.php is this:
  1. Create a session record to get a session_id value.
  2. Score the roles based on user input and store those scores.
  3. Score the patterns based on user input and store those scores.
If we throw an exception after (1) but before (2), there will be no match_roles nor match_sessions records for the session.  If we throw an exception after (2) but before (3), there will be no match_patterns records for the session.

If a user gets to an output screen that shows a role and four patterns, all of 1-3 have occurred. If a user sees a screen with partial output, we didn't make it. That's not happening lately, but it was in the early stages of testing.
